version: "3"
services:
  postgres:
    image: postgres:11.4-alpine
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
  redis:
    image: redis:7.0.4-alpine3.16
    container_name: redis
    restart: always
    depends_on:
      - postgres
    ports:
      - 6379:6379
  app:
    env_file:
      - ./.env
    build: .
    container_name: app
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/code
    ports:
      - 5000:5000
  celery:
    env_file:
      - ./.env
    build: .
    command: celery -A celeryd worker --loglevel=INFO --purge
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
      - app
  celery-beat:
    env_file:
      - ./.env
    build: .
    command: celery -A celeryd beat --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
      - celery
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    env_file:
      - ./.env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
